import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:roost_app/main.dart';
import 'package:roost_app/pages/auth/welcome_page.dart';
import 'package:roost_app/pages/onboarding/onboarding_page.dart';
import 'package:roost_app/services/auth_service.dart';
import 'package:roost_app/widgets/common/roost_logo_icon.dart';
import 'package:roost_app/services/country_service.dart';

/// The ONLY splash impression a user should see is the native Android
/// launch screen (android/app/src/main/res/drawable*/splash.png,
/// generated by flutter_native_splash from assets/icon/roost_icon.png).
/// main() calls FlutterNativeSplash.preserve() to keep that native view
/// on screen past Flutter's first frame; this widget's job is to
/// resolve the auth/onboarding routing check, hold for a comfortable
/// minimum so the native splash doesn't flash by too fast, then call
/// FlutterNativeSplash.remove() and hand off -- all as ONE continuous
/// native splash view, never a second Flutter-rendered splash screen
/// underneath it. Native splash screens can't hold a real multi-second
/// custom animation themselves (a hard platform limitation -- Android
/// discourages prolonging them, and pre-Android-12 devices support no
/// animation at all), so this preserve/remove handoff is the actual
/// documented pattern for controlled splash timing, not a workaround.
class SplashPage extends StatefulWidget {
  const SplashPage({super.key});

  @override
  State<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {
  /// Comfortable minimum time the native splash stays up, regardless of
  /// how fast routing resolves -- long enough to read as a deliberate
  /// beat, short enough to stay within what Android's own splash
  /// screen guidance considers reasonable (not an artificial multi-
  /// second hold fighting the platform).
  static const _minimumDisplay = Duration(milliseconds: 2800);

  bool _isLoggedIn = false;
  bool _onboardingCompleted = false;

  @override
  void initState() {
    super.initState();
    _navigateToNext();
  }

  Future<void> _prepareRouting() async {
    try {
      await CountryService.instance.init();
      _isLoggedIn = await AuthService.isLoggedIn();
      final prefs = await SharedPreferences.getInstance();
      _onboardingCompleted = prefs.getBool('onboarding_completed') ?? false;
    } catch (_) {
      // Fields already default to false/false -- worst case on an
      // unexpected failure here is routing to Onboarding, which is
      // always safe, rather than leaving the user stuck.
    }
  }

  Future<void> _navigateToNext() async {
    // Whichever takes longer wins -- the native splash is guaranteed to
    // stay up for at least _minimumDisplay, but routing prep taking
    // longer than that (slow disk, cold start) doesn't get cut short.
    await Future.wait([
      Future.delayed(_minimumDisplay),
      _prepareRouting(),
    ]);

    try {
      FlutterNativeSplash.remove();
    } catch (_) {
      // No-op in environments without a real native splash view (e.g.
      // widget tests) -- never let this block navigation.
    }

    if (!mounted) return;

    if (!_isLoggedIn) {
      if (!_onboardingCompleted) {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(builder: (_) => const OnboardingPage()),
        );
      } else {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(builder: (_) => const WelcomePage()),
        );
      }
    } else {
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(builder: (_) => const HomePage()),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    // Matches the native splash exactly (black background, same logo)
    // -- this is hidden behind the preserved native view for virtually
    // this whole screen's lifetime, but stays visually identical on the
    // off chance of any brief gap during the OS's own dismiss
    // transition, rather than showing something that could look like a
    // different, second splash.
    return const Scaffold(
      backgroundColor: Colors.black,
      body: Center(
        child: RoostLogoIcon(size: 160),
      ),
    );
  }
}
